"""add reference_code table (Phase 5b.2 — Reference Data as per-code reviewable object)

Reference Data becomes a per-code reviewable object: each distinct code in a coded column
is its own row carrying Value / Meaning / Origin / Status, reviewable and frozen per code
(not whole-tab). This is the first governance slice built DIRECTLY on Postgres (behind the
``database.refdata_backend`` flag, default ``yaml``) rather than migrated from an existing
DuckDB store.

Columns:
  * element_key  — ``source|schema|table|column`` (the ElementStateStore key shape); a code
                   list belongs to one coded column.
  * code         — the observed/declared code value (stringified; ``(null)`` for a null code).
  * value        — the code's expanded / full-word form (steward-entered).
  * meaning      — the code's business meaning (steward-entered).
  * origin       — ``profiled`` (default) | ``declared``. Manual dropdown; a declared code is
                   one hand-added that the profiler did not observe.
  * status       — per-code lifecycle: ``blank`` | ``draft`` | ``in_review`` | ``approved``.
                   5b.2 reaches up to ``in_review`` (Save draft + partial Submit); ``approved``
                   arrives via migration of already-approved fields and via the Review Workspace
                   queue in 5b.3. Approved rows are frozen.

Per-code lifecycle events reuse the generic ``lifecycle_transition`` table
(``subject_type='reference_code'``, ``subject_ref='<element_key>|<code>'``).

NO hard delete (governance object); temporal audit of value/meaning edits is a later slice.
"""
from __future__ import annotations

from alembic import op

revision = "0005_reference_code"
down_revision = "0004_cde_and_provenance"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE reference_code (
            id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            element_key   TEXT NOT NULL,
            code          TEXT NOT NULL,
            value         TEXT,
            meaning       TEXT,
            origin        TEXT NOT NULL DEFAULT 'profiled',
            status        TEXT NOT NULL DEFAULT 'blank',
            submitted_at  TIMESTAMPTZ,
            submitted_by  TEXT,
            approved_at   TIMESTAMPTZ,
            approved_by   TEXT,
            created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT reference_code_origin_check CHECK (origin IN ('profiled','declared')),
            CONSTRAINT reference_code_status_check CHECK (status IN ('blank','draft','in_review','approved')),
            CONSTRAINT uq_reference_code_element_code UNIQUE (element_key, code)
        );
        """
    )
    op.execute("CREATE INDEX ix_reference_code_element ON reference_code (element_key);")
    op.execute("CREATE INDEX ix_reference_code_status ON reference_code (element_key, status);")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS reference_code;")
