"""add audit_events table (prepone Audit → Postgres, 2026-08-03)

Mirrors the DuckDB ``audit_events`` schema (``core/audit/store.py``) so the append-only
audit log can move off the process-lifetime DuckDB file lock — a chief cause of the
single-writer "used by another process" failures on a second ``uvicorn`` — onto Postgres,
behind the ``database.audit_backend`` flag (default ``duckdb``).

Append-only event log: one row per business/AI event. ``id`` is an identity column
(``BY DEFAULT`` so the from-DuckDB migration can preserve existing ids); ``payload`` is
JSONB. Indexes mirror the DuckDB store (occurred_at, event_type, subject).
"""
from __future__ import annotations

from alembic import op

revision = "0007_audit_events"
down_revision = "0006_canonical_lifecycle"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE audit_events (
            id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            occurred_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
            event_class   TEXT NOT NULL,
            event_type    TEXT NOT NULL,
            actor_user_id TEXT,
            actor_role    TEXT,
            legal_entity  TEXT,
            subject_type  TEXT,
            subject_id    TEXT,
            payload       JSONB,
            request_id    TEXT
        );
        """
    )
    op.execute("CREATE INDEX ix_audit_events_occurred_at ON audit_events (occurred_at);")
    op.execute("CREATE INDEX ix_audit_events_event_type ON audit_events (event_type);")
    op.execute("CREATE INDEX ix_audit_events_subject ON audit_events (subject_type, subject_id);")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS audit_events;")
